export const NAVIGATION = {
  CHANGE_ACTIVE_PATH: 'NAVIGATION.CHANGE_ACTIVE_PATH',
  SET_PAGE_LOADING: 'NAVIGATION.SET_PAGE_LOADING',
  SET_QUERY: 'NAVIGATION.SET_QUERY',
  SET_LINK_BEFORE_AUTH: 'NAVIGATION.SET_LINK_BEFORE_AUTH',
};

export const DEAL_LIST = {
  LOAD_PENDING: 'DEAL_LIST.LOAD_PENDING',
  LOAD_SUCCESS: 'DEAL_LIST.LOAD_SUCCESS',
  LOAD_FAIL: 'DEAL_LIST.LOAD_FAIL',
  UPDATE_PENDING: 'DEAL_LIST.UPDATE_PENDING',
  UPDATE_SUCCESS: 'DEAL_LIST.UPDATE_SUCCESS',
};

export const SETTINGS_INFO = {
  LOAD_PENDING: 'SETTINGS_INFO.LOAD_PENDING',
  LOAD_SUCCESS: 'SETTINGS_INFO.LOAD_SUCCESS',
  LOAD_FAIL: 'SETTINGS_INFO.LOAD_FAIL',
  UPDATE_PENDING: 'SETTINGS_INFO.UPDATE_PENDING',
  UPDATE_SUCCESS: 'SETTINGS_INFO.UPDATE_SUCCESS',
};

export const SETTINGS_UPDATE_TRADE_BUDGET = {
  EDIT_PENDING: 'SETTINGS_UPDATE_TRADE_BUDGET.EDIT_PENDING',
  EDIT_SUCCESS: 'SETTINGS_UPDATE_TRADE_BUDGET.EDIT_SUCCESS',
  EDIT_FAIL: 'SETTINGS_UPDATE_TRADE_BUDGET.EDIT_FAIL',
  RESET_STATUS: 'SETTINGS_UPDATE_TRADE_BUDGET.RESET_STATUS',
};
