export const NAVIGATION = {
  CHANGE_ACTIVE_PATH: 'NAVIGATION.CHANGE_ACTIVE_PATH',
  SET_PAGE_LOADING: 'NAVIGATION.SET_PAGE_LOADING',
  SET_QUERY: 'NAVIGATION.SET_QUERY',
  SET_LINK_BEFORE_AUTH: 'NAVIGATION.SET_LINK_BEFORE_AUTH',
};
